DEMO_RESULT = {
    "overall_score": 7,
    "intro": "Twoja twarz ma kilka wyraźnych atutów — dobra struktura i jakość skóry to solidna baza do dalszej pielęgnacji.",
    "strengths": [
        "Dobra jakość skóry — równomierny koloryt bez widocznych przebarwień",
        "Wyraźnie zarysowany owal twarzy i linia żuchwy",
        "Pełna objętość policzków — twarz wygląda świeżo i wypoczęcie",
        "Okolica oczu bez wyraźnych oznak zmęczenia",
    ],
    "concerns": [
        "Pierwsze drobne zmarszczki dynamiczne w okolicy czoła — warto zadziałać profilaktycznie",
        "Lekko widoczne naczynka na policzkach — można zredukować laser naczyniowym",
        "Skóra mogłaby zyskać na nawilżeniu i rozświetleniu",
    ],
    "treatments": [
        "Toksyna botulinowa",
        "Laser naczyniowy",
        "Mezoterapia",
        "Peelingi chemiczne",
    ],
    "areas": {
        "okolica_oczu":  8,
        "jakosc_skory":  7,
        "zmarszczki":    7,
        "napiecie":      7,
        "owal_twarzy":   8,
        "przebarwienia": 8,
        "naczynka":      6,
    },
    "area_labels": {
        "okolica_oczu":  "Okolica oczu",
        "jakosc_skory":  "Jakość skóry",
        "zmarszczki":    "Zmarszczki",
        "napiecie":      "Napięcie twarzy",
        "owal_twarzy":   "Owal twarzy",
        "przebarwienia": "Przebarwienia",
        "naczynka":      "Naczynka / Rumień",
    },
    "lang": "pl",
}
