DEMO_RESULT = {
    "overall_score": 7,
    "intro": "Twoja skóra jest w dobrej kondycji z kilkoma obszarami, które warto wzmocnić.",
    "strengths": ["Jakość skóry", "Owal twarzy", "Przebarwienia"],
    "concerns":  ["Naczynka / Rumień", "Zmarszczki", "Napięcie skóry"],
    "strengths_items": [
        {"label": "Jakość skóry",   "score": 8},
        {"label": "Owal twarzy",    "score": 8},
        {"label": "Przebarwienia",  "score": 8},
    ],
    "concerns_items": [
        {"label": "Naczynka / Rumień", "score": 6},
        {"label": "Zmarszczki",        "score": 7},
        {"label": "Napięcie skóry",    "score": 7},
    ],
    "treatments": [
        "Toksyna botulinowa",
        "Laser naczyniowy",
        "Mezoterapia",
    ],
    "areas": {
        "okolica_oczu":  8,
        "jakosc_skory":  8,
        "zmarszczki":    7,
        "napiecie":      7,
        "owal_twarzy":   8,
        "przebarwienia": 8,
        "naczynka":      6,
    },
    "area_labels": {
        "okolica_oczu":  "Okolica oczu",
        "jakosc_skory":  "Jakość skóry",
        "zmarszczki":    "Zmarszczki",
        "napiecie":      "Napięcie twarzy",
        "owal_twarzy":   "Owal twarzy",
        "przebarwienia": "Przebarwienia",
        "naczynka":      "Naczynka / Rumień",
    },
    "health_note": "Pamiętaj, że regularne stosowanie filtra SPF 50+ to podstawa ochrony przed fotostarzeniem.",
    "lang": "pl",
    "biological_age_min": 32,
    "biological_age_max": 36,
    "user_age": 40,
    "user_height": 170,
    "user_weight": 68.0,
    "user_bmi": 23.5,
}
