DEMO_RESULT = {
    "overall_score": 7,
    "intro": "Twoja skóra jest w dobrej kondycji z kilkoma obszarami, które warto wzmocnić.",
    "strengths": ["Jakość skóry", "Owal twarzy", "Przebarwienia"],
    "concerns":  ["Naczynka / Rumień", "Zmarszczki", "Napięcie skóry"],
    "strengths_items": [
        {"label": "Jakość skóry",  "score": 8, "key": "skin_quality"},
        {"label": "Owal twarzy",   "score": 8, "key": "face_oval"},
        {"label": "Przebarwienia", "score": 8, "key": "pigmentation"},
    ],
    "concerns_items": [
        {"label": "Naczynka / Rumień", "score": 6, "key": "vessels"},
        {"label": "Zmarszczki",        "score": 6, "key": "wrinkles"},
        {"label": "Napięcie skóry",    "score": 6, "key": "skin_tension"},
    ],
    "treatments": [
        "Toksyna botulinowa (relaksacja mięśni mimicznych)",
        "Laser naczyniowy (redukcja naczynek i rumienia)",
        "Mezoterapia (nawilżenie i rewitalizacja skóry)",
        "Nici liftingujące (poprawa napięcia i owalu twarzy)",
    ],
    "areas": {
        "okolica_oczu":  7,
        "jakosc_skory":  8,
        "zmarszczki":    6,
        "napiecie":      6,
        "owal_twarzy":   8,
        "przebarwienia": 8,
        "naczynka":      6,
    },
    "area_labels": {
        "okolica_oczu":  "Okolica oczu",
        "jakosc_skory":  "Jakość skóry",
        "zmarszczki":    "Zmarszczki",
        "napiecie":      "Napięcie twarzy",
        "owal_twarzy":   "Owal twarzy",
        "przebarwienia": "Przebarwienia",
        "naczynka":      "Naczynka / Rumień",
    },
    "health_note": "Regularne stosowanie filtra SPF 50+ to podstawa ochrony przed fotostarzeniem. Warto również zadbać o odpowiednie nawodnienie skóry od wewnątrz.",
    "lang": "pl",
    "biological_age_min": 34,
    "biological_age_max": 38,
    "user_age": 45,
    "user_height": 172,
    "user_weight": 74.0,
    "user_bmi": 25.0,
}
